In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고가 뜨지 않도록..
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['font.size'] = 16
plt.rcParams['figure.figsize'] = 20, 10
plt.rcParams['axes.unicode_minus'] = False

# 저장
import pickle

# 딥러닝
import tensorflow as tf

# 딥러닝 신경망 구조를 정의하는 것.
from tensorflow.keras.models import Sequential
# 층 구조를 정의하는 것
from tensorflow.keras.layers import Dense
# 활성화 함수를 정의하는 것
from tensorflow.keras.layers import Activation

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 현재 프로젝트를 GPU에 할당한다.
# 사용한 가능한 GPU 목록을 가져온다.
gpus = tf.config.experimental.list_physical_devices('GPU')
# gpu가 있다면...
if len(gpus) > 0 :
    try :
        for gpu in gpus :
            tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError as e :
        print(e)


### 평균 제곱 오차
- 진짜 결과와 예측된 결과가 얼마나 차이나는지 살펴본다.
- 진짜 결과와 예측된 결과의 차이를 제곱하여 합산하고 그 평균을 구한다. 
![3](image/3.png)

In [2]:
# 입력 데이터
공부한시간 = [2,4,6,8]
# 결과 데이터
성적 = [81,93,91,97]

In [3]:
# 기울기와 y절편
기울기 = 2.3
y절편 = 79.0


In [4]:
# 학습 데이터를 통해 예측 성적을 계산한다. 
예측성적 = []

for v1 in 공부한시간 :
    a1 = (기울기 * v1) + y절편
    예측성적.append(a1)
    
예측성적


[83.6, 88.2, 92.8, 97.4]

In [5]:
# 계산의 편리성을 위해 ndarray를 생성한다.
array1 = np.array(성적)
array2 = np.array(예측성적)

print(array1)
print(array2)


[81 93 91 97]
[83.6 88.2 92.8 97.4]


In [6]:
# 진짜 결과와 예측 결과를 뺀다
array3 = array1 - array2
array3

array([-2.6,  4.8, -1.8, -0.4])

In [7]:
# 제곱을 구한다
array4 = array3 ** 2
array4

array([ 6.76, 23.04,  3.24,  0.16])

In [8]:
# 평균을 구한다
mse = array4.mean()
mse

8.299999999999985