In [2]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고가 뜨지 않도록..
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['font.size'] = 16
plt.rcParams['figure.figsize'] = 20, 10
plt.rcParams['axes.unicode_minus'] = False

# 출력 창 청소
from IPython.display import clear_output

import time


# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 딥러닝
import tensorflow as tf

# 딥러닝 모델 구조를 정의하는 것
from tensorflow.keras.models import Sequential
# 층 모델(은닉층과 출력층)
from tensorflow.keras.layers import Dense
# 활성화 함수를 정의하는 것
from tensorflow.keras.layers import Activation

# 데이터 표준화
from sklearn.preprocessing import StandardScaler
# 문자열을 숫자로 변환
from sklearn.preprocessing import LabelEncoder
# 원핫인코딩
from tensorflow.keras.utils import to_categorical

# GPU 할당
gpus = tf.config.experimental.list_physical_devices('GPU')
# GPU가 있다면..
if len(gpus) > 0 :
    try :
        for gpu in gpus :
            tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError as e :
        print(e)


In [3]:
# 랜덤 시드 설정
np.random.seed(1)
tf.random.set_seed(1)

In [4]:
# 데이터를 읽어온다.
df1 = pd.read_csv('data/iris.csv', header=None)
df1.columns = ['꽃받침길이', '꽃받침너비', '꽃잎길이', '꽃잎너비', '품종']
df1


꽃받침길이  꽃받침너비  꽃잎길이  꽃잎너비              품종
0      5.1    3.5   1.4   0.2     Iris-setosa
1      4.9    3.0   1.4   0.2     Iris-setosa
2      4.7    3.2   1.3   0.2     Iris-setosa
3      4.6    3.1   1.5   0.2     Iris-setosa
4      5.0    3.6   1.4   0.2     Iris-setosa
..     ...    ...   ...   ...             ...
145    6.7    3.0   5.2   2.3  Iris-virginica
146    6.3    2.5   5.0   1.9  Iris-virginica
147    6.5    3.0   5.2   2.0  Iris-virginica
148    6.2    3.4   5.4   2.3  Iris-virginica
149    5.9    3.0   5.1   1.8  Iris-virginica

[150 rows x 5 columns]

In [5]:
# 데이터 프레임의 정보 확인
df1.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   꽃받침길이   150 non-null    float64
 1   꽃받침너비   150 non-null    float64
 2   꽃잎길이    150 non-null    float64
 3   꽃잎너비    150 non-null    float64
 4   품종      150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [6]:
# 결측치확인
df1.isna().sum()


꽃받침길이    0
꽃받침너비    0
꽃잎길이     0
꽃잎너비     0
품종       0
dtype: int64

In [7]:
# 입력과 결과로 나눈다.
X = df1.drop('품종', axis=1)
y = df1['품종']

display(X)
display(y)


꽃받침길이  꽃받침너비  꽃잎길이  꽃잎너비
0      5.1    3.5   1.4   0.2
1      4.9    3.0   1.4   0.2
2      4.7    3.2   1.3   0.2
3      4.6    3.1   1.5   0.2
4      5.0    3.6   1.4   0.2
..     ...    ...   ...   ...
145    6.7    3.0   5.2   2.3
146    6.3    2.5   5.0   1.9
147    6.5    3.0   5.2   2.0
148    6.2    3.4   5.4   2.3
149    5.9    3.0   5.1   1.8

[150 rows x 4 columns]

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: 품종, Length: 150, dtype: object

In [8]:
# 문자열 데이터를 숫자로 변환한다.
encoder1 = LabelEncoder()
encoder1.fit(y)
y = encoder1.transform(y)
y


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
# 데이터 표준화
scaler1 = StandardScaler()
scaler1.fit(X)
X = scaler1.transform(X)
X


array([[-9.00681170e-01,  1.03205722e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00, -1.24957601e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.38535265e+00,  3.37848329e-01, -1.39813811e+00,
        -1.31297673e+00],
       [-1.50652052e+00,  1.06445364e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.02184904e+00,  1.26346019e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-5.37177559e-01,  1.95766909e+00, -1.17067529e+00,
        -1.05003079e+00],
       [-1.50652052e+00,  8.00654259e-01, -1.34127240e+00,
        -1.18150376e+00],
       [-1.02184904e+00,  8.00654259e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.74885626e+00, -3.56360566e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
        -1.44444970e+00],
       [-5.37177559e-01,  1.49486315e+00, -1.28440670e+00,
        -1.31297673e+00],
       [-1.26418478e+00,  8.00654259e-01, -1.22754100e+00,
      

In [10]:
# 원핫 인코딩 수행
# 분류의 경우에는 결과 데이터가 0부터 1씩증가되는 형태라고 하더라도
# 연속성을 가진 데이터가 아닌 각각의 별개의 데이터를 의미한다.
# 딥러닝은 무조건 회귀분석을 수행하기 때문에 원핫 인코딩을 통해
# 연속성을 가지지 않는 형태의 데이터로 만들어 학습 시켜야 한다.
y_encoded = to_categorical(y)
y_encoded


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [11]:
# 신경망 구조를 설계한다.
model = Sequential()

a1 = X.shape[1]
model.add(Dense(16, input_dim=a1))
model.add(Activation('relu'))

# 결과 데이터의 종류가 3가지..
model.add(Dense(3))
# 다중 분류이므로....
model.add(Activation('softmax'))


In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                80        
                                                                 
 activation (Activation)     (None, 16)                0         
                                                                 
 dense_1 (Dense)             (None, 3)                 51        
                                                                 
 activation_1 (Activation)   (None, 3)                 0         
                                                                 
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [16]:
# 손실함수
# 다중 분류이므로 categorical_crossentropy
model.compile(loss='categorical_crossentropy', optimizer='adam', 
              metrics=['accuracy'])


In [17]:
# 학습한다.
model.fit(X, y_encoded, epochs=50, batch_size=10)


Epoch 1/50
15/15 [==============================] - 1s 3ms/step - loss: 1.1271 - accuracy: 0.3600
Epoch 2/50
15/15 [==============================] - 0s 3ms/step - loss: 1.0280 - accuracy: 0.4067
Epoch 3/50
15/15 [==============================] - 0s 3ms/step - loss: 0.9421 - accuracy: 0.4733
Epoch 4/50
15/15 [==============================] - ETA: 0s - loss: 0.9176 - accuracy: 0.60 - 0s 3ms/step - loss: 0.8619 - accuracy: 0.5667
Epoch 5/50
15/15 [==============================] - 0s 3ms/step - loss: 0.7971 - accuracy: 0.7200
Epoch 6/50
15/15 [==============================] - ETA: 0s - loss: 0.7419 - accuracy: 0.90 - 0s 3ms/step - loss: 0.7388 - accuracy: 0.7333
Epoch 7/50
15/15 [==============================] - 0s 3ms/step - loss: 0.6896 - accuracy: 0.7000
Epoch 8/50
15/15 [==============================] - 0s 3ms/step - loss: 0.6451 - accuracy: 0.7133
Epoch 9/50
15/15 [==============================] - 0s 3ms/step - loss: 0.6072 - accuracy: 0.7333
Epoch 10/50
15/15 [===============

In [18]:
# 성능 확인
a1 = model.evaluate(X, y_encoded)
print(f'손실률 : {a1[0]}')
print(f'정확도 : {a1[1]}')


5/5 [==============================] - 0s 3ms/step - loss: 0.1783 - accuracy: 0.9533
손실률 : 0.1782946139574051
정확도 : 0.95333331823349


In [20]:
a1 = model.predict(X)
pred = np.argmax(a1, axis=-1)
pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [21]:
r1 = accuracy_score(y, pred)
r1


0.9533333333333334